title: Phoenix
description: Phoenix Documentation
theme: just-the-docs
logo: "/assets/images/phoenix app logo.svg"

color_scheme: dark
url: https://just-the-docs.github.io

aux_links:
  phcode.dev : https://phcode.dev
  Getting Started: https://phcode.dev
